CREATE TABLE bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) ,
    location varchar(255)
);

CREATE table customer (
    id BIGINT generated by default as identity PRIMARY KEY,
    first_name varchar(255),
    last_name varchar(255),
    email varchar(255),
    birth_date DATE
);

CREATE table bank_account (
    id BIGINT generated by default as identity primary key,
    account_num varchar(255),
    balance double precision,
    customer_id BIGINT,
    bank_id  BIGINT,

    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer(id),
    CONSTRAINT fk_bank FOREIGN KEY (bank_id) REFERENCES bank(id)

);



CREATE table transaction (
    id BIGINT generated by default as identity primary key,
    amount double precision,
    time_stamp timestamp,
    transaction_type varchar(100),
    sender_id BIGINT,
    receiver_id BIGINT,

    CONSTRAINT fk_sender foreign key (sender_id) references bank_account(id),
    constraint fk_receiver foreign key (receiver_id) references bank_account(id)
);

