CREATE TABLE bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    location varchar(255)
);

CREATE TABLE human (
    id BIGINT GENERATED by default as identity primary key,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255),
    birth_date DATE,
    bank_id BIGINT,
    CONSTRAINT fk_human_bank FOREIGN KEY (bank_id) REFERENCES bank(id)
);

CREATE TABLE bank_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_num VARCHAR(20) UNIQUE NOT NULL,
    balance DECIMAL(19,2) NOT NULL,
    human_id BIGINT,
    CONSTRAINT fk_bank_account_human FOREIGN KEY (human_id) REFERENCES human(id)
);


